### PR TITLE
just putting in a link to youtube and a video feedback of an input to…

### PR DESCRIPTION
**Pull request by dotcan15**
… SVQ class

### CODE REVIEW

**Comment by dotcan15** [comment]
Hi Sally
I’m obviously doing something wrong and not embedding the links to the memory box stories and the youtube film on the Dot can project page, as they don’t appear as a hyper link on my browser any idea’s what I might be doing wrong ?

Cheers
John


John Arthur

Recovery Coaching Development Manager

& Digital Inclusion Worker

John works Mondays - Wednesdays

Tel - 0131 556 8765, Mobile – 07894244071


[cid:image001.jpg@01D0948C.F1039320]<http://www.comas.org.uk/self-directed-support.php>[cid:image002.jpg@01D0948C.F1039320]<http://www.comas.org.uk/co-production-in-health.php>[cid:image003.jpg@01D0948C.F1039320]<http://www.comas.org.uk/women-in-recovery.php>[cid:image004.jpg@01D0948C.F1039320]<http://www.serenitycafe.co.uk/>[cid:image005.jpg@01D0948C.F1039320]<http://www.comas.org.uk/burnout-options-page.php>

[cid:image006.jpg@01D0948C.F1039320]
8 Jackson’s Entry | Edinburgh | EH8 8PJ
0131 556 8765 | www.comas.org.uk<http://www.comas.org.uk/>

Help us with a donation, every little helps<http://www.charitychoice.co.uk/comas>

Scottish Charity SCO39670 | Company Ltd SC363674

**Comment by SallyDyson** [comment]
Hi John,

I'll have a chat to Rikki and Andy on Monday - they are our experts.

Have a great weekend

Sally

**Comment by dotcan15** [comment]
Thanks Sally
Have a great weekend ☺
J

John Arthur

Recovery Coaching Development Manager

& Digital Inclusion Worker

John works Mondays - Wednesdays

Tel - 0131 556 8765, Mobile – 07894244071


[cid:image001.jpg@01D094B0.DC70F690]<http://www.comas.org.uk/self-directed-support.php>[cid:image002.jpg@01D094B0.DC70F690]<http://www.comas.org.uk/co-production-in-health.php>[cid:image003.jpg@01D094B0.DC70F690]<http://www.comas.org.uk/women-in-recovery.php>[cid:image004.jpg@01D094B0.DC70F690]<http://www.serenitycafe.co.uk/>[cid:image005.jpg@01D094B0.DC70F690]<http://www.comas.org.uk/burnout-options-page.php>

[cid:image006.jpg@01D094B0.DC70F690]
8 Jackson’s Entry | Edinburgh | EH8 8PJ
0131 556 8765 | www.comas.org.uk<http://www.comas.org.uk/>

Help us with a donation, every little helps<http://www.charitychoice.co.uk/comas>

Scottish Charity SCO39670 | Company Ltd SC363674

**Comment by Oppecmo** [comment]
Hi John, 

I've fixed that for you. The issue with the Memory Box link you forgot to close the link out with a ")" that is why it was not properly hyperlinking. As for the YouTube link, you had the link just copied in, to have it show up correctly you have to format it in the same way that the Memory Box link was done. Link text in [] and the link itself in (). 

Hope that helps! :) 

RIkki

**Pull request merged**
